language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git --save
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "myintelex"
  - git config user.email "myintelex@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/myintelex/myintelex.github.io.git
